### PR TITLE
Support Spring Data paging out of the box

### PR DESCRIPTION
**Pull request by vjroby**
Added mapper and adapter for spring page.

### CODE REVIEW

**Comment by temecom** [comment]
Is this moving to a releasable state? We are trying to implement pagination based on SpringBoot and have not been able to arrive at a satisfactory solution.

**Comment by kaqqao** [comment]
@temecom Yes! I have been delayed by various life occurrences, but am ready to release the next version of the starter this week. Paging should work out of the box with a few tunable options.

**Comment by miguelocarvajal** [comment]
I am also looking for paging support out of the box for reactive repositories.

It'd be great if this worked out of the box! What's the status on this? If not implemented I would be willing to take a stab at it with some guidance.

Thanks

**Comment by miguelocarvajal** [comment]
@kaqqao bump! Any hints on the best way to implement this?

**Comment by blagerweij** [comment]
@kaqqao: Any chance of getting a basic implementation for Page/Slice? For me, it would be sufficient to provide support like Spring Data does this: support the optional `Pageable` parameter in the methods, so we can limit the (top-level) results. Full support for relay/edge/nodes etc could be version 2.0

**Comment by kaqqao** [comment]
Sorry everyone, I've been away for a while so the project didn't receive much action. I'm back and actively working on it, and will release a new version with this included soon. Thanks for the patience!

**Comment by blagerweij** [comment]
Thanks for your response, really looking forward to new updates. This library looks very well designed and is promising, but appears to be dependent on one / a few developers. Really appreciate your commitment on this :-)

**Comment by blagerweij** [comment]
Have you been able to make any progress on the above ?

**Comment by kaqqao** [comment]
Merged this one manually. Took my sweet time but it's finally in master 😅

**Pull request closed without merging**
